name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Checkstyle
        run: make checkstyle

  cov:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Coverage
        run: |
          cd backend/shortesttm_path
          mvn clean verify -DskipTests -Dmaven.javadoc.skip=true