name: Deploy Javadoc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-javadoc:
    name: Deploy Javadoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Generate Javadoc
        run: make javadoc
      - name: Deploy Javadoc
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./backend/shortesttm_path/target/reports/apidocs