name: Deploy Javadoc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-javadoc:
    name: Deploy Javadoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Javadoc
        run: |
          cd backend/shortesttm_path
          mvn clean javadoc:javadoc
          cd target/reports
          git init
          git checkout -b gh-pages
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Deployed Javadoc"
          git remote add origin https://github.com/antoinebrunet1/shortesttm-path
          git push origin gh-pages